### PR TITLE
[chore] documentation update for #21

### LINKED ISSUE #21: Provide balanced installation/contribution instructions
Both the installation section and the contribution section tell me to use nix as the first option. In the worst case, this will make an uninformed newcomer install nix and go down a rabbit hole of tooling nightmares (YMMV).

I suggest to be a bit more balanced. Cabal and Stack are by far the most popular options to build haskell projects: https://taylor.fausak.me/2022/11/18/haskell-survey-results/#s3q0

I don't see a `stack.yaml` in this repo either.

### PR DESCRIPTION
**Pull request by MangoIV**
does this look more like what you would imagine @hasufell? 

may close #21

### CODE REVIEW

**Comment by MangoIV** [comment]
cabal install probably doesn't work, does it? I have no idea how to install things globally anymore, I don't do such things :D

**Comment by hasufell** [comment]
The language is still confusing and insinuating that there's something wrong with not using nix.

Instead, all options should be listed in order of their popularity (not for political correctness, but to avoid steering uninformed users into unnecessary directions).

- cabal: `cabal install` (maybe with a link to the docs about binary install location)
- stack: `stack install` (link to docs might be useful too)
- nix:. ... (with a note that this is a proper package manager with its own ecosystem, not really a simple tool to get started with Haskell)

**Comment by hasufell** [comment]
> well nix is just “first class” in this repo

Why is cabal not first class?

**Comment by MangoIV** [comment]
while I make sure that this works with as many GHC versions as possible, if I don’t pin tools, I cannot guarantee for the user, that coming to this repo, they’ll find a working hls, formatter, linter, ghc, cabal-install without nix. They’ll have to care for that themselves. Nix is in that way “easier”. 

Please don’t take this as me saying something’s wrong with using cabal or cabal itself, it’s really not that, I just think that nix is useful for not having to care about setting up a dev environment, I can kinda do that for them :)

**Comment by hasufell** [comment]
What tools does the user need to build this project that can't be installed through cabal's [build-tool-depends](https://cabal.readthedocs.io/en/stable/cabal-package-description-file.html#pkg-field-build-tool-depends)?

Otherwise it would seem like a bug in your cabal file if it relies on things in PATH other than ghc.

> I cannot guarantee for the user, that coming to this repo, they’ll find a working hls, formatter, linter, ghc, cabal-install without nix

GHC, cabal and HLS are supported through ghcup. Formatters and linters are provided through HLS plugins without the need for binaries in PATH.

Also, this only applies to the contribution section. Not to the installation section.

----

Also, this is just my opinion. It's your project, so feel free to ignore my remarks.

**Comment by MangoIV** [comment]
No it’s fine, you’re right I should make it more clear that you don’t “need” nix to use this. :)

**Comment by MangoIV** [comment]
I think I’ll postpone this PR until I have clarity wrt the hackage namespace. Then it’ll be much easier to install with cabal itself. Afaik it doesn’t understand things like “cabal install git+https://github.com/mangoiv/cabal-audit” does it?

**Comment by hasufell** [comment]
It understands URLs pointing to tarballs though: `cabal install https://hackage.haskell.org/package/ghcup-0.1.22.0/ghcup-0.1.22.0.tar.gz`

**Pull request closed without merging**
